version: "3"
services:
  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"  # Spark Master UI
      - "7077:7077"  # Spark Master Cluster Port
      - "4040:4040"  # Spark Job UI
    volumes:
      - spark_data:/opt/spark/work

  spark-worker:
    image: apache/spark:latest
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"  # Spark Worker UI
    volumes:
      - spark_data:/opt/spark/work

volumes:
  spark_data:
